version: '3.8'
services:
  apicongress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apicongress
    env_file:
      - .env
    environment:
      - PORT=5000
    ports:
      - "8080:5000" # Host port 8080 → Container port 5000
    restart: unless-stopped
  
  nginx:
    image: nginx:alpine
    container_name: congress-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - apicongress
    restart: unless-stopped