version: '3.8'
services:
  apicongress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apicongress
    env_file:
      - .env
    environment:
      - PORT=5000
    ports:
      - "8080:5000" # Host port 8080 → Container port 5000
    restart: unless-stopped