name: Deploy APICongress
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy-apicongress:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy APICongress
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          timeout: 1800s
          command_timeout: 600s
          script: |
            # Go to the deployment directory
            cd /opt/apicongress/APICongress || mkdir -p /opt/apicongress/APICongress && cd /opt/apicongress/APICongress
            
            # If a git repository exists, update it; otherwise, clone it
            if [ -d ".git" ]; then
              echo "Updating existing repository..."
              git fetch --all
              git reset --hard origin/main
            else
              echo "Cloning repository..."
              git clone git@github.com:isaacbrendel/APICongress.git .
            fi
            
            # Create or update .env file with GitHub secrets
            echo "Creating/updating .env file with API keys..."
            cat > .env << EOL
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            CLAUDE_API_KEY=${{ secrets.CLAUDE_API_KEY }}
            COHERE_API_KEY=${{ secrets.COHERE_API_KEY }}
            GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
            GROK_API_KEY=${{ secrets.GROK_API_KEY }}
            EOL
            
            # Build and deploy the new containers
            docker compose down --remove-orphans || true
            docker compose build --no-cache
            docker compose up -d
            sleep 10
            docker compose ps
            docker compose logs --tail=50 apicongress