name: Deploy APICongress
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-apicongress:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy APICongress
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          timeout: 1800           # 30 minutes total session timeout
          command_timeout: 600    # 10 minutes per command
          script: |
            cd /opt/apicongress

            # Stop old containers
            docker compose down --remove-orphans || true

            # Remove old code
            rm -rf .* * || true

            # Clone fresh
            git clone git@github.com:YourUser/APICongress.git .

            # Build and run
            docker compose build --no-cache
            docker compose up -d

            # Wait
            sleep 10

            # Logs
            docker compose ps
            docker compose logs --tail=50 apicongress
