name: Deploy APICongress
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-apicongress:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy APICongress
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          timeout: 1800s           # 1800 seconds (30 minutes)
          command_timeout: 600s    # 600 seconds (10 minutes) per command
          script: |
            # 1) Backup
            mkdir -p /tmp/apicongress_backup
            cd /opt/apicongress
            [ -f .env ] && cp .env /tmp/apicongress_backup/

            # 2) Stop containers 
            docker compose down --remove-orphans

            # 3) Remove old code
            rm -rf .* * || true

            # 4) Clone fresh
            echo "Cloning APICongress repository..."
            git clone git@github.com:YourUser/APICongress.git .

            # 5) Restore .env if needed
            [ -f /tmp/apicongress_backup/.env ] && cp /tmp/apicongress_backup/.env .

            # 6) Build and run
            echo "Building and running new containers..."
            docker compose build --no-cache
            docker compose up -d

            # 7) Wait for containers to start
            sleep 10

            # 8) Show logs
            echo "===== Docker Compose Status ====="
            docker compose ps
            docker compose logs --tail=50 apicongress

            # 9) Cleanup
            rm -rf /tmp/apicongress_backup
